NVIDIA/Q2RTX

setup/find-retail-paks.sh

Custom install location breaks for all default Steam installs as the space in the directory 'Quake 2' causes only the first part of the path to be passed. Fixes error: ```./find-retail-paks.sh: line 14: pushd: /mnt/steam/steamapps/common/Quake: No such file or directory```

Fix custom install to work

---

src/refresh/vkpt/device_memory_allocator.c
src/refresh/vkpt/god_rays.c
src/refresh/vkpt/transparency.c
src/refresh/vkpt/uniform_buffer.c

Looks like this code was copy-pasted from C++11 code. Luckily, C99 allows to not specify the type but it would default to `int`.

vkpt: fix type definition from auto(which is storage specifier in C) to corresponding types

---

src/baseq2/g_spawn.c

This change makes the nomonsters 1 console option, which inhibits members of the "monster" class from being spawned on level load, also apply to the members of the "misc_deadsoldier" and "misc_insane" classes. If you're turning off the enemies for sightseeing, there's no need for those classes either.

Remove insane and dead soldiers with nomonsters 1

---

setup/find-retail-paks.sh

There's no reason why this script has to fail if it's run before q2rtx.sh. mkdir -p won't give an error if that directory already exists.

Make setup more robust to script order.

---

src/refresh/vkpt/transparency.c

Call the floating-point absolute value function instead of the integer version.
(Found with [PVS-Studio](https://www.viva64.com/en/pvs-studio/))

Call fabsf() instead of abs()

---

src/refresh/vkpt/main.c
src/refresh/vkpt/shader/global_ubo.h
src/refresh/vkpt/shader/tone_mapping_apply.comp

One of the effects that's currently "lost" in RTX mode is the "full screen blend", where a color is mixed into the final image (literally, an alpha blended screen-covering rectangle). It's used for certain in-game events, eg damage received, item pickups, active effects (quad damage) - that has certainly value for the player. It's also used to give everything a murky color when underwater (so, for atmosphere of a sort).
I added the "full-screen blend" into the tone mapping step, after the final image, but before the tonemapping.
The motivation to add it there, and not the "final_blit" shader, was that I guess making it work with colors not mapped to [0,1] would be more useful if proper HDR output is ever added.

Reintroduce 'full screen blend'

---

inc/client/video.h
inc/refresh/refresh.h
src/client/main.c
src/client/screen.c
src/unix/sdl2/video.c
src/windows/glimp.c

Contains the following changes:
* A fix in CL_Frame() causing from physics & refresh intervals in `SYNC_ASYNC` case
* Display "refresh" FPS on screen instead of "client FPS" (the latter may run faster) - "refresh" FPS is probably what most people expect
* Port a number of `maxfps`-related patches from Q2PRO. Notably, it contains a change to inform the user when the requested `maxfps` value can not be achieved exactly.
All in all, these changes should address the complaints from #117.

Fixes for FPS display, for #117

---

src/refresh/vkpt/main.c

`cmd_buffers_compute` was removed earlier, but not from this block of code only used in debug builds.

Fix debug builds for compute buffer removal

---

src/refresh/vkpt/material.c

The material table entry wasn't indexed, so that function only looked at the first material in the table, all the time.

Fix MAT_ResetUnused()

---

src/refresh/vkpt/draw.c
src/refresh/vkpt/main.c
src/refresh/vkpt/vkpt.h

A well-behaved Vulkan application should not care about the number of swapchain images exposed by vkGetSwapchainImagesKHR.
In XWayland (right now), there is no IMMEDIATE mode, only MAILBOX, which is exposed as IMMEDIATE.
However, this means that the max number of swapchain images exceeds what would normally be expected for typical IMMEDIATE implementations under X11.
With this change I can run Quake 2 RTX under XWayland on my Radeon VII.
This will also likely be needed by NVIDIA following the release of their 470 driver which enables [X]Wayland support.
Signed-off-by: Joshua Ashton <joshua@froggi.es>

Remove MAX_SWAPCHAIN_IMAGES limit for XWayland

---

inc/common/files.h
inc/refresh/refresh.h
src/CMakeLists.txt
src/client/ui/playermodels.c
src/common/bsp.c
src/common/files.c
src/refresh/images.c
src/refresh/models.c
src/refresh/vkpt/bsp_mesh.c
src/refresh/vkpt/models.c
src/refresh/vkpt/textures.c
src/refresh/vkpt/vkpt.h

...such as those you'd find in the GOG version of Quake II.
* A 32-bit dedicated server build is provided, so old `gamex86.dll` game libraries can be used.
* Inhibition of other config files when `autoexec.cfg` is present was removed. That behavior broke mods that rely on `default.cfg` being executed.
* Texture and model asset loading was adjusted so a baseq2 "better quality" asset doesn't automatically override assets from the game. This is allows mods to actually replace models, textures and images.
Limitations:
* Since it's a dedicated server, only multiplayer games work.
* No Linux support. It should probably work, but I don't really have any i386 mods to test with.
But hey, it's enough to play against some bots -
start a server with `q2rtxded_x86.exe +set game eraser`, set `bot_num` …

Improve support for old mods

---

inc/refresh/images.h
inc/refresh/refresh.h
inc/shared/shared.h
src/refresh/images.c
src/refresh/vkpt/bsp_mesh.c
src/refresh/vkpt/main.c
src/refresh/vkpt/material.c
src/refresh/vkpt/material.h
src/refresh/vkpt/textures.c
src/refresh/vkpt/vkpt.h

For lighting, Q2RTX predominantly uses light-emitting surfaces. The amount of light a surface should emit is determined by an entry in the materials list and an "emissive" texture associated with a material. Material definitions and, if appropriate, emissive textures are provided for basically all baseq2 materials.
Unfortunately, if an emissive texture is not present, a surface won't emit light. This is a problem for maps that use materials beyond the baseq2 set - ie from mods or mission packs (see also #77).
Fortunately, the original light information is still present: the `SURF_LIGHT` flag indicates that a surface should emit light.
With this information "old" maps could be lit much more like they were intended to.
This patch adds a check for `LIGHT` surfaces and the ability to …

Add support for BSP "LIGHT" surfaces

---

inc/format/bsp.h
src/common/bsp.c

This needs testing, and some back&forth with qbism (see https://github.com/qbism/q2tools-220/issues/11) who has been implementing an "extended limits" format similar to BSP2 into their compiler.
I did test the load in q2pro itself, and it seemed to work, although obviously network limitations need to be addressed separately and that's not in the scope of this push since that requires breaking compatibility.

QBSP support (for extended limits)

---

inc/refresh/refresh.h
readme.md
src/refresh/vkpt/bsp_mesh.c
src/refresh/vkpt/material.c
src/refresh/vkpt/material.h
src/refresh/vkpt/textures.c
src/refresh/vkpt/vkpt.h

This allows use of the new material system/editor to toggle "fake emissive" image generation and to change the brightness threshold used by that.
For an example, start rmine1 with these materials:
```
textures/r_mine/walmine01:
texture_base textures/r_mine/walmine01.wal
is_light 1
synth_emissive 1
emissive_threshold 150
textures/e2u1/ceil1_26:
texture_base textures/e2u1/ceil1_26.wal
is_light 1
synth_emissive 1
emissive_threshold 200
```
* This makes the "red ore" glow, similar to the blue ore
* Fixes a light texture to actually emit light (visible eg below the computer in that control room)
In general, wrt your changes to the material system: cool stuff :)

Make 'fake emissive' material properties editable

---

src/refresh/vkpt/bsp_mesh.c
src/refresh/vkpt/main.c
src/refresh/vkpt/vkpt.h

Change the color of poly lights with multiple frames. For #134
Previously, for materials consisting of multiple frames, only the emissive data from the first frame would be used to set up the poly light. (The mitigation was to not create poly lights from animated materials.)
Now, poly light colors are updated as well when the "world" is animated.
Some properties are different from frame to frame but can't change dynamically; they're dealt with as such:
* `is_light` property: As soon as a single frame has this property a poly light is created.
* emissive area: This is the bounding area of all emissive areas of the frames.
Other properties (e.g. `emissive_factor`) still apply per frame.

Animate poly lights

---

src/refresh/vkpt/shader/tone_mapping_histogram.comp

Barriers in not dynamically uniform control flow are forbidden by the specification. This change moves such barriers present in the tone mapping histogram shader outside of the divergent code.

Fix for barrier in not dynamically uniform control flow.

---

src/refresh/vkpt/asvgf.c

`vkpt_taa()` uses `pipeline_layout_taa`, but `vkpt_asvgf_create_pipelines()` specifies `pipeline_layout_general` in the setup.
This currently more of a cosmetic issue than a real problem as the layouts are pretty much the same.

Fix apparent pipeline layout mismatch in asvgf.c

---

src/refresh/vkpt/path_tracer.c

Silences the following validation errors that appeared with the latest Vulkan SDK:
validation layer 2 4096: Validation Error: [ VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03674 ] Object 0: handle = 0x27ecae4f478, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xea5edaf3 | vkBuildAccelerationStructuresKHR(): The buffer associated with pInfos[0].scratchData.deviceAddress was not created with VK_BUFFER_USAGE_STORAGE_BUFFER_BIT bit. The Vulkan spec states: The buffer from which the buffer device address pInfos[i].scratchData.deviceAddress is queried must have been created with VK_BUFFER_USAGE_STORAGE_BUFFER_BIT usage flag (https://vulkan.lunarg.com/doc/view/1.2.189.0/windows/1.2-extensions/vkspec.html#VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03674)

Create buf_accel_scratch with VK_BUFFER_USAGE_STORAGE_BUFFER_BIT

---

src/server/save.c

Seems to work fine... also confirmed in/fixes #150.

By default, disable GMF_ENHANCED_SAVEGAMES checks

---

inc/refresh/refresh.h
src/refresh/vkpt/main.c
src/refresh/vkpt/profiler.c
src/refresh/vkpt/shader/tone_mapping_apply.comp
src/refresh/vkpt/shader/tone_mapping_curve.comp
src/refresh/vkpt/tone_mapping.c
src/refresh/vkpt/vkpt.h

I'm currently playing around with tonemapping, and here are some related bits and pieces that I have accumulated...
Most significant is probably b4c2b3f: This tries to address an issue where the tonemapping curve has a "valley" in certain dark areas (see below for illustration: both the curve, as well as a location where this happens, here the basement in base1).
By default, that "valley" isn't visible (due to the Reinhard mixed in), but for the screenshot I set `tm_reinhard` to 0 so it can be perceived: some areas suddenly have a sort-of "negative" effect, like the walls left and right of the cross hair having a part that's darker than it's neighboring parts.
Since my attempt to address this is basically an empirically determined "fudge factor" I think a second opinion would be good here …

Tonemapping: debug aids, tweaks

---

baseq2/q2rtx.menu
cmake/compileShaders.cmake
inc/refresh/images.h
inc/refresh/refresh.h
src/client/refresh.c
src/refresh/gl/main.c
src/refresh/images.c
src/refresh/vkpt/bloom.c
src/refresh/vkpt/conversion.h
src/refresh/vkpt/draw.c
src/refresh/vkpt/fsr.c
src/refresh/vkpt/main.c
src/refresh/vkpt/shader/fsr_easu.glsl
src/refresh/vkpt/shader/fsr_easu_fp16.comp
src/refresh/vkpt/shader/fsr_easu_fp32.comp
src/refresh/vkpt/shader/fsr_rcas.glsl
src/refresh/vkpt/shader/fsr_rcas_fp16.comp
src/refresh/vkpt/shader/fsr_utils.glsl
src/refresh/vkpt/shader/global_ubo.h
src/refresh/vkpt/shader/stretch_pic.frag
src/refresh/vkpt/shader/tone_mapping_apply.comp
src/refresh/vkpt/shader/utils.glsl
src/refresh/vkpt/tone_mapping.c
src/refresh/vkpt/vkpt.h

This builds upon the basic approach outlined by #83 ("pick float16 surface format") and updates various systems for HDR.
Tonemapping: This tweaks the current algorithm to disable the "knee" for bringing things into range and clamping/sRGB conversion. Extending the brightness range is done by applying a (user-configurable) scale after tonemapping; seems to work and look well enough.
Screenshots: They can be written in the Radiance `.hdr` format. The main motivation for using this was simplicity: STB comes with an HDR writer. Viewers are available online (eg https://viewer.openhdr.org/) and standalone (eg https://github.com/wkjarosz/hdrview).
Other tweaks include:
* Adjustments to FSR shaders to handle HDR values
* User-configurable UI brightness

HDR support

---

src/refresh/vkpt/bsp_mesh.c

Fixes #163.
`cluster == -1` seems to be a legitimate case as that value is set in `bsp_mesh.c:719`.
I didn't dig deeper into the circumstances under which that happens (though it may be worthwhile, if only for documentation/commenting purposes).
But, as can be seen from the code, that value causes an out-of-bounds array access.
Curiously, this access would happen on Windows as well, not just Linux; I guess it's only manifesting as a crash there due to compiler differences (codegen, or perhaps data alignment/arrangement) or ABI differences.

Check for negative cluster number in compute_sky_visibility()

---

src/refresh/vkpt/main.c
src/refresh/vkpt/textures.c

Split pt_nearest into two variables (the second one is named pt_nearest_2d), and default it to on, to match other Q2 engines/not cause blurry low quality UI textures.
Also fixes blurry non-standard fonts, since it was hardcoded to blur only the main font.

separate out nearest filtering for UI, default it on

---

src/refresh/vkpt/shader/instance_geometry.comp
src/refresh/vkpt/shader/vertex_buffer.h

Fix missing texture animation on bsp models (issue #185) by "animating" the frame in `load_and_transform_triangle()`.
Another approach I considered was to go over each bsp model once per frame and animating the material on each primitive - think similar principle as `instance_geometry`, only for bsp models, and material animation only.
I went for the `load_and_transform_triangle()` approach mainly because it's simpler.
However, it may have a performance disadvantage, as the "animation" would potentially be done quite a number of times, compared for guaranteed once per frame in the approach above.
(Perhaps it would be worthwhile to implement that as well and check if there's a measurable performance difference.)

Fix bsp model texture animation

---

src/refresh/images.c

Most importantly this fixes a crash that currently occurs when making a HDR screenshot.
On top of that some small tweaks and async writing support were added.

HDR screenshot crash fix & improvements

---

src/refresh/vkpt/bsp_mesh.c
src/refresh/vkpt/shader/indirect_lighting.rgen

Background:
After a bit of a while I looked at some custom maps again, specifically some which use very few "baseq2" textures and rely on `SURF_LIGHT` faces for lighting quite a bit.
The issue:
Suddenly all the walls very way too bright...
Turns out the map author used textures, including the wall textures, _mostly_ for "normal" surfaces, but _sometimes_ for emissive surfaces!
However, the code currently handling light surfaces with materials not specified in the material system sets `MATERIAL_FLAG_LIGHT` if a material is encountered on an emissive surface (`SURF_LIGHT`) - so one occurrence of that and suddenly all uses emit light!
Attempt 1:
My first thought was to treat surfaces lacking the `SURF_LIGHT` as always non-emissive.
However, this breaks quite a few updated materials that add …

Fixes for lighting in custom maps

---

src/refresh/vkpt/textures.c

Certain combinations of settings make Q2RTX eat video memory like popcorn, and more than's healthy at that, possibly causing performance issues. Try to detect when that happens and print a warning (together with some advice).
This happened to me after changing to 4K output resolution... my DRS max scale was still set to 150%, causing my poor og 3080 with it's 10GB of vram to choke noticeably. 
While I want to point out this would not have happened with default settings, I figure this may happen to other people as well - so print a warning if a suspiciously large amount of memory is used for screen-space memory. (Though I wonder if it makes sense to have it more prominent - e.g. displaying it in the menu.)
However, what I'm not sure about is how well this works when using multiple GPUs...

Print a warning if screen-space image memory usage is very high

---

src/refresh/vkpt/vertex_buffer.c

Another instance of lightstyle clamping that was probably missed in 95e84a440bef694e982961ef9b994b554ac1357f.

Fix lightstyle range in vkpt_light_buffer_upload_to_staging()

---

baseq2/q2rtx.menu

Screen blending can be switched on or off in GL mode, but not in RTX mode.
Also added controls to fine-tune the effect. Should help for cases like in #207.

Add screen blending controls for RTX mode

---

src/refresh/images.c
src/refresh/vkpt/material.c

Some games override baseq2 assets without changing the name -
e.g. 'action' replaces models/weapons/v_blast with something looking completely differently.
Using the material definition from baseq2 makes things look wrong.
So try to detect if the game is overriding a texture from baseq2 and, if that is the case, ignore the material definition (if it's from baseq2 - to allow for a game-specific material definition).
(I previously submitted something with the same intent as part of #116 [[2415da2](https://github.com/NVIDIA/Q2RTX/pull/116/commits/2415da21620e07aeada906780097512ac7689efd)], but it seems those changes got lost or ineffective during the material system overhaul.)

Ignore a material definition if a game overrides a texture

---

src/refresh/vkpt/bsp_mesh.c
src/refresh/vkpt/material.c
src/refresh/vkpt/material.h

The previous approach decided on the fallback radiance value based on whether the emissive image was fake or not.
However, there are cases where having a synthesized emissive texture to be "always emissive" is beneficial -
e.g. the material was sometimes used as an emissive surface, but in other cases manually placed lights were used (and the "BSP radiance" is 0).
Since we don't support point lights, having the surface take over lighting duties here is helpful.
(If you want a practical example: `textures/dark_1/0text_59` on xatrix' `xswamp` map.)
This PR also contains non-related developer and user quality of life changes.

 materials: Make fallback radiance (used when no BSP radiance given) an explicit attribute

---

baseq2/q2rtx.menu

Fix a typo in the menu

---

src/refresh/vkpt/bsp_mesh.c
src/refresh/vkpt/material.c
src/refresh/vkpt/material.h

…instead of the image_base width & height.
This allows to re-use the same "base" texture for multiple materials, even if
the original textures have different dimensions/aspect ratios.
Previously, when doing so, the image's width/height members would be repeatedly
overwritten, and whatever original texture was loaded last, that dimensions
would "win". When the various original textures had different aspect ratios
some texture scaling factors would've been wrong (and the texture appear
distorted).
(This doesn't occur with Q2RTX materials, but I stumbled upon that when creating some custom materials.)

Store a material's "original" texture dimensions in special members

---

CMakeLists.txt

…to avoid a LNK4098 linker warning.
Specifically, adjusting the C++ flags is needed now b/c oal-soft uses it.

Also adjust /MD flag in CMAKE_CXX_FLAGS_* variables

---

src/refresh/vkpt/main.c
src/refresh/vkpt/shader/light_lists.h
src/refresh/vkpt/shader/path_tracer_rgen.h
src/refresh/vkpt/shader/primary_rays.rgen
src/refresh/vkpt/shader/vertex_buffer.h
src/refresh/vkpt/vertex_buffer.c
src/refresh/vkpt/vkpt.h

This is a different approach at addressing #226 after the changes #227 fell short in other scenarios.
I introduced a small _history_ of "cluster light counts" used for light selection.
Now, if light sampling is performed with an "old" RNG seed, we can pull out the light count used at that time from that history we're keeping around (based on the frame number, which is conveniently stored in the RNG seed as well).
This seems to work quite well - it fixes both the problem from #226 but crucially doesn't seem to make things worse if the number of lights in a cluster changes, as previously visible in e.g. the single-player entrance of the `security` map.
(Actually, I'd like to argue that `security` looks _better_ now, as now the "flashing" at the start, due to jumps in the max light count, is …

 Keep a small history of 'light counts' for each cluster used for sampling lights (for #226)

---

src/refresh/vkpt/material.c

Fixes incorrect scaling of textures w/o a custom material definition (ie custom textures on custom maps, most likely) after #222.

Also store material original dimensions if no material definition is available

---

src/refresh/vkpt/textures.c

Missed a place were 4 bytes per texture pixel are assumed, which is not correct since #214 introduced 16bpc gray scale texture support.

Fix texture data size computation for R16_UNORM textures

---

.gitmodules

the old repository wasn't updated since 2021!
that is the correct repository with a lively activity

Update .gitmodules pointing to the correct SDL2 repo

---

baseq2/q2rtx.menu

FPS can now be adjusted in increments of 1 instead of 10 (useful for displays with "odd" frequencies such as [138 Hz](https://rog.asus.com/us/monitors/above-34-inches/rog-swift-oled-pg42uq-model/), 144 Hz, 165 Hz, …). The maximum FPS for the DRS target is now 250 to accomodate for 240 Hz displays, which is becoming a viable target on high-end GPUs and low settings.
The slider can be dragged with the mouse if you need to change its value quickly.

Allow more precise adjustments for DRS frames per second target

---

src/refresh/vkpt/main.c

pPhysicalDeviceGroupProperties must be a valid pointer to an array of pPhysicalDeviceGroupCount VkPhysicalDeviceGroupProperties structures, so the caller is responsible for initializing the base fields.
Fix crash with gfxreconstruct. (https://github.com/LunarG/gfxreconstruct/pull/902)

Fix uninitialized VkPhysicalDeviceGroupProperties

---

src/refresh/vkpt/main.c

Fix graphics/transfer queue selection to correctly pick the same queue on platforms that dont support split queues. this also preseve's the preference for split queues.
Remove unused request for sparseBindings, allows running on platforms that dont support it like mesa's ANV driver.
Without these fixes initialization fails either due to missing a transfer queue or missing sparseBinding on mesa's ANV driver for Arc GPUs.

Fix up vulkan initialization

---

src/refresh/vkpt/main.c

We can accept them during surface picking, but we need to set an SRGB format on the swapchain image view in that case.
Should help with https://github.com/NVIDIA/Q2RTX/issues/217, as Wayland on NVIDIA currently only exposes UNORM output surfaces.

Add support for UNORM RGB8 output surface formats

---

src/refresh/vkpt/bsp_mesh.c

`NODRAW` surfaces would be double-collected by collecting with `filter_nodraw_sky_lights()`, exceeding the amount of allocated primitives.

Fix primitive overflow with pt_bsp_sky_lights > 1

---

src/refresh/vkpt/material.c

Was accessing a NULL pointer in one case, and not setting the values in another. Now, even if we get `R_NOTEXTURE` for a base image, use that for original dimensions.
Won't crash and at least somewhat consistent.

Fixes for pbr_material_t::original_width and original_height for missing textures

---

src/refresh/vkpt/draw.c
src/unix/video.c

Adds a bunch of fixes to make Q2RTX run on Wayland. Hopefully fixes #217.
Note that this contains some changes (dcd28504cd3b122e77962ae2152e41a8858d4f84, 269ad3cec304ac230d88f48988b9e7670d69ba6b) that may actually be issues somewhere in the software stack I used (Wayland on NVIDIA) - they may not be necessary for Wayland on AMD, but I can't test that.

Wayland support

---

src/refresh/vkpt/shader/path_tracer_rgen.h

Spherical lights used to be the only type of dynamic lights, but after spot light support has been added, they have been renamed to 'dynamic lights' in the code. Well, except these places.
(Only identifiers have been changed, no changes to logic.)

shader: Rename instances of 'spherical' to 'dynamic' (for lights)

---

src/refresh/vkpt/main.c
src/refresh/vkpt/material.c
src/refresh/vkpt/shader/constants.h
src/refresh/vkpt/shader/path_tracer_rgen.h
src/refresh/vkpt/shader/primary_rays.rgen
src/refresh/vkpt/shader/reflect_refract.rgen

...to make them look a bit more interesting.
Some maps use a TRANS flag with various "random" textures which are not intended to be used as "glass" and don't have the GLASS material kind set, and even with that, may look bad due to their colors not working well as "throughput" colors.
So keep them acting as a "non-physical see-through material", but apply some distortion to the "through" ray.
Before:
After:
(Location is in xatrix' xcompnd1 map.)

Apply distortion effect on TRANS walls

---

src/client/view.c

...as it's not valid. Fixes NVIDIA#294

Don't use predicted_angles for flashlight direction during demo playback

---

inc/refresh/refresh.h
src/baseq2/g_local.h
src/baseq2/g_spawn.c
src/client/precache.c
src/client/refresh.c
src/client/screen.c
src/refresh/gl/gl.h
src/refresh/gl/sky.c
src/refresh/vkpt/main.c

This is necessary to stop the sky in some rerelease maps, eg base1,
from spinning: these maps set a 'skyrotate' value, but explicitly
disable it with the new 'skyautorotate'.

Add 'skyautorotate' worldspawn property as found in rerelease game.

---

inc/shared/config.h

On my Linux ppc64le machine, the `q2rtxded` does not look up correct `gameppc64le.so`
```
./q2rtxded
```
Expected: `Loaded game library from /home/tle/Games/q2rtx/baseq2/gameppc64le.so`
Actual: `Can't access /home/tle/Work/Q2RTX/baseq2/gamex86.so: No such file or directory****`
It turns out the `CPUSTRING` is not handled correctly for Linux ppc64le
Fixes https://github.com/NVIDIA/Q2RTX/issues/304

Update CPUSTRING for ppc64le

---

.github/workflows/build.yml

To denote that the binaries are for Linux x86_64. Because there are many 64bit architectures for Linux right now, personally I find `x64` can be confusing.

Rename the Linux artefact output

---

src/common/msg.c

...introduced in 0f5ef84b9168ff483e9dd8a5ad43c19e74f1f83b
An input check condition required some tweaking which was missed when porting a commit.

Fix an incorrect check 

---

src/client/client.h
src/client/entities.c
src/client/main.c
src/client/view.c

Following up on https://github.com/NVIDIA/Q2RTX/issues/318

Scale the view weapon to prevent intersection with walls

---

src/client/sound/dma.c

Inadvertently removed in #317.
Makes loudness in OpenAL and software modes comparable again.

Make 'software' audio volume logarithmic again

---

inc/common/protocol.h
src/client/entities.c
src/client/main.c
src/client/parse.c
src/client/sound/main.c
src/server/entities.c

"When GMF_CLIENTNUM feature was introduced, it was expected that client
POV number will only be set to valid client slot numbers in range [0,
255). Therefore, clientNum has been transmitted as a byte, with 255
(CLIENTNUM_NONE) reserved for a special case to indicate no current POV
number (this has always been buggy, see below).
However, one might want to set client POV to any entity >= 256, not just
client entitites (to view the game from monster POV, for example). Thus,
make clientNum strictly mean ‘number of POV entity minus 1’ and transmit
it as a short in range [-1, MAX_EDICTS - 1).
To accomodate older Q2PRO clients, reset clientNum to client slot number
and zero out POV entity modelindex if clientNum is >= 255.
clientNum == -1 is legal, and can happen e.g. when playing a MVD without …

Sync with Q2PRO: Protocol extension for large clientnums

---

src/server/init.c
src/server/server.h

It is written in server savegame file and should be kept intact.

Sync with Q2PRO: Keep original mapcmd intact in SV_ParseMapCmd().

---

doc/server.md
inc/client/sound/sound.h
inc/common/protocol.h
inc/refresh/refresh.h
inc/server/server.h
src/client/cin.c
src/client/client.h
src/client/keys.c
src/client/main.c
src/client/parse.c
src/client/refresh.c
src/client/screen.c
src/client/sound/main.c
src/refresh/gl/draw.c
src/refresh/gl/gl.h
src/refresh/gl/main.c
src/refresh/gl/texture.c
src/refresh/vkpt/draw.c
src/refresh/vkpt/main.c
src/refresh/vkpt/vkpt.h
src/server/commands.c
src/server/init.c
src/server/main.c
src/server/server.h
src/server/user.c

Somewhat analogous to Ogg support, cinematics support was first ported to Q2RTX from Yamagi, but Q2PRO got it's own cinematics support at a later date.
There isn't really anything that made Yamagi's cinematics support special, so just replace it wholesale with the implementation from Q2PRO.
Notable changes:
* The way the cinematics frame is drawn, Q2PRO added dedicated render functions for "raw" images. (The RTX implementation still registers images internally, though.)
* For letterboxed cinematics, the letterbox sizes are stored and are removed on playback. So for a good part, the old Quake 2 intro is now actually fullscreen on 16:9 display. Neat!

Sync with Q2PRO: Cinematics

---

src/client/sound/ogg.c

Not setting 'ogg_status == STOP' meant that the attempts to play the track again all resulted in no change, since OGG_PlayTrack() thought the track was already being played.

Fix Ogg music looping logic

---

baseq2/materials/baseq2.mat

The "power shield" model - visible when eg attacking a monster_brain - shows up as a green, but dark, glassy surface, hardly visible. Make it more noticeable by adding an emissive component.

More pronounced/visible power shield effect

---

src/refresh/vkpt/shader/reflect_refract.rgen

This fixes sky not showing up behind transparent surfaces if `pt_enable_nodraw` is set to 1.
FWIW, I suspect that the `found_intersection(...)` check was there for a reason?
Do you remember why and/or recall any scenarios when getting the sky color may look ugly?

Always obtain sky color if reflection hit nothing

---

doc/client.md
src/refresh/vkpt/bsp_mesh.c

The way material kind adjustment & filtering interacted caused, in practice, all "sky" surfaces to be removed if pt_enable_nodraw was set. However, I observed that "fake sky blocks" for lighting would have a meterial that's not a default "sky" material, but something else. In these cases, it would be better to keep "real" sky surfaces (so they eg continue providing lighting) but remove the "fake lighting" surfaces; I changed the material kind adjustment & filtering to work like this. The old behavior is provided by setting pt_enable_nodraw to 2.

Tweak how NODRAW/SKY surfaces are filtered.

---

inc/client/ui.h
inc/common/utils.h
inc/refresh/images.h
inc/refresh/refresh.h
inc/server/server.h
src/client/client.h
src/client/console.c
src/client/demo.c
src/client/main.c
src/client/refresh.c
src/client/screen.c
src/client/ui/demos.c
src/client/ui/menu.c
src/client/ui/playerconfig.c
src/client/ui/script.c
src/client/ui/servers.c
src/client/ui/ui.c
src/client/ui/ui.h
src/common/cmd.c
src/common/common.c
src/common/utils.c
src/refresh/gl/draw.c
src/refresh/gl/gl.h
src/refresh/gl/main.c
src/refresh/images.c
src/refresh/vkpt/draw.c
src/refresh/vkpt/main.c
src/refresh/vkpt/vkpt.h
src/server/mvd/client.c

A bunch of upstream changes/improvements to the UI.

Sync with Q2PRO: UI stuff

---

src/common/bsp.c

Split BSP_ParseExtensions() into two stages: header parsing to calculate amount of extra space to reserve on hunk, and actual lump loading.
Makes FACENORMALS parsing nicer.

Sync with Q2PRO: Generalize parsing BSPX extensions.

---

src/client/entities.c
src/refresh/gl/mesh.c

Purpose of this flag is unknown. It doesn't seem to do anything useful. Effectively, it just disables entity origin interpolation in CL_AddPacketEntities(), and requires the renderer to do interpolation instead. Use of RF_FRAMELERP also requires old_origin to be always valid. While Q2PRO server guarantees this, other servers may not.
RF_FRAMELERP is actually harmful: because lerp_origin is stepped discretely, effects like particle trails look odd on RF_FRAMELERP entities. Also, since Q2PRO renderer only interpolates origin if RF_FRAMELERP is set, interpolation of linked entities with this flag cleared is broken.
Simply remove special handling of RF_FRAMELERP from client and renderer.
Fixes choppy enemy movement in GL renderer, introduced by 5e2a2d30e8d2101e272a14eff4f93281230aed4f.

Don't special handle RF_FRAMELERP on the client.

---

inc/common/async.h
inc/system/pthread.h
inc/system/system.h
src/CMakeLists.txt
src/client/http.c
src/common/async.c
src/common/common.c
src/refresh/images.c
src/unix/system.c
src/windows/pthread.c
src/windows/system.c

Adds a pthread "emulation" for Windows.
A number of upstream changes make use of these threading changes, so this is a prerequisite for future porting of the former.

Sync with Q2PRO: Windows pthread support

---

inc/common/cvar.h
inc/common/files.h
src/common/common.c
src/common/files.c

More upstream filesystem changes (mostly related to game dir handling).

Sync with Q2PRO: More filesystem changes

---

baseq2/q2rtx.menu
doc/client.md
src/refresh/vkpt/main.c
src/refresh/vkpt/shader/constants.h
src/refresh/vkpt/shader/projection.glsl

Added the Panini projection, specifically the "cylindrical stereographic" version with the parameter D = 1.0
D can be any value in order to seamlessly scale between projections:
D = 0 gives the rectilinear projection
D = +inf should give the "cylindrical
orthographic projection"
More info in this paper on why Panini is natural for the human eye:
http://dx.doi.org/10.2312/COMPAESTH/COMPAESTH10/009-016
Question:
Perhaps the Panini and Stereographic projections should be given a lower pt_projection values, as these are the most useful next to rectilinear? Cylindrical, mercator, etc. are just for demonstration, but very disorienting to use in an actual game.

Added Panini Projection to pt_projection

---

src/refresh/vkpt/main.c

...which is actually true for `PROJECTION_CYLINDRICAL`.

Fix gcc warning that fov_scale may be used uninitialized

---

src/refresh/vkpt/shader/fsr_easu.glsl
src/refresh/vkpt/shader/fsr_rcas.glsl

When combined with DSR pixels not from this frames might have been fetched, resulting in incorrect output near the borders, which becomes very visible when water warp is enabled.
Found while investigating https://github.com/NVIDIA/Q2RTX/pull/376#issuecomment-1949584336

FSR: Clamp input coords when fetching TAA output, to avoid issues near borders

---

inc/common/common.h
src/common/common.c

Small changes from upstream: tweak "last error" handling, and remove an unused function.

Sync with Q2PRO: Error stuff from common

---

doc/client.md
src/client/locs.c

Upstream changes to the client-side locations feature.

Sync wirh Q2PRO: Locations

---

doc/client.md
doc/server.md

Miscellaneous documentation changes from upstream.

Sync with Q2PRO: Docs

---

.gitmodules

As title, the v1.3 is known to have issue with compilation on Fedora 40 (which comes with gcc 14.0.1). The v1.3.1 has addressed all of those issues.

Bump zlib to 1.3.1

---

src/refresh/stb/stb.c
src/refresh/vkpt/textures.c

This is the long-awaited rewrite that is **2-5x faster scalar, 4-12x faster w/SIMD**
Fortunately our code does not use any deprecated functions so porting is quite trivial

Port to stb_image_resize2

---

.github/workflows/build.yml

The runtime is based on Debian 11 of which libraries and compiler are 2 years newer than that of v2. Steam has officially accepted games that runs on v3.
The main motivation behind this change is to gain access to more up-to-date libs and compilers. That means we do not have to introduce backward compatibility patches in libraries should the upstream maintainers decides to cut support for old compilers.

Update steamrt to v3 (sniper)

---

src/refresh/vkpt/main.c
src/refresh/vkpt/uniform_buffer.c

I've been working on adding `VK_KHR_ray_query` support to turnip, the open-source Vulkan driver for Qualcomm Adreno GPUs. These are fixes I needed to get Q2RTX running in combination with a [Mesa MR](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/28447). The performance at the moment isn't that great, however.

Fixes for turnip

---

src/refresh/vkpt/main.c

Mesa's X11 WSI has a `minImageCount` of 3. Using only two images "works", but introduces considerable slowdown. Fix this by respecting the implementation's 'minImageCount`.

Always allocate at least minImageCount swapchain images

---

src/refresh/vkpt/path_tracer.c

It is inefficient to record multiple vkCmdBuildAccelerationStructuresKHR back-to-back - for example, RADV will implicitly barrier between each build. To fix this, record AS build parameters into a temporary batch struct and call vkCmdBuildAccelerationStructuresKHR once for the entire batch.

Dispatch acceleration structure builds in batches

---

src/server/save.c

Fixes https://github.com/NVIDIA/Q2RTX/issues/413

Use real file system paths when saving and loading games

---

src/unix/system.c

It may have been returned from getenv()...
Hopefully fixes #420.

Don't unconditionally free() xdg_data_home_dir

---

inc/common/bsp.h
src/common/common.c
src/common/features.h

Informational message about optional features built into the engine.

Sync with Q2pro: Print compiled features in developer mode

---

src/common/pmove.c
src/server/mvd/client.c
src/server/user.c

Some smaller fixes and tweaks.

Sync with Q2pro: Misc fixes & tweaks

---

doc/server.md
src/server/commands.c
src/server/main.c

Changes from upstream relating to server commands.

Sync with Q2PRO: Server-related tweaks

---

inc/shared/atomic.h
inc/shared/platform.h
src/client/http.c
src/windows/system.c

Some small upstream changes more or less related to Windows & MSVC.

Sync with Q2PRO: Windows-, MSVC-related things

---

src/refresh/vkpt/draw.c
src/refresh/vkpt/main.c
src/refresh/vkpt/vkpt.h

* We're supposed to use `VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT` only if `VK_EXT_color_space` is available.
* The stretch_pic renderpass references the surface format, so recreate the renderpass if the swapchain changed.

Fix validation errors related to HDR

---

src/refresh/vkpt/shader/stretch_pic.vert

Latest Vulkan SDK complained about it.

Mark SBO in stretch_pic VP as readonly, to silence validation error

---

src/refresh/vkpt/textures.c

The intention was clearly to choose the "linear_clamp" sampler for bloom images. This happens correctly in vkpt_create_images().
The removed code happened to set clamping on any unlucky skin/wall/etc texture that happened to have the same indices as the values of VKPT_IMG_BLOOM_*.

Fix incorrect sampler override in vkpt_textures_update_descriptor_set()

---

inc/client/client.h
inc/client/keys.h
inc/common/cvar.h
inc/common/msg.h
inc/common/net/net.h
inc/common/protocol.h
inc/refresh/refresh.h
inc/shared/game.h
inc/shared/shared.h
src/client/client.h
src/client/screen.c
src/client/ui/ui.h
src/common/bsp.c
src/common/msg.c
src/common/net/chan.c
src/refresh/gl/gl.h
src/refresh/gl/main.c
src/refresh/gl/surf.c
src/refresh/gl/world.c
src/server/ac.c
src/server/mvd/game.c
src/server/server.h

Upstream switched to using a macro to specify bitmasks, making them more readable than hex values or `1 << x` style values.
Also using enums instead of macros for some constants.

Sync with Q2PRO: Enums & bitmasks changes

---

src/refresh/vkpt/device_memory_allocator.c
src/refresh/vkpt/device_memory_allocator.h
src/refresh/vkpt/draw.c
src/refresh/vkpt/main.c
src/refresh/vkpt/path_tracer.c
src/refresh/vkpt/precomputed_sky.c
src/refresh/vkpt/textures.c
src/refresh/vkpt/transparency.c
src/refresh/vkpt/uniform_buffer.c
src/refresh/vkpt/vertex_buffer.c
src/refresh/vkpt/vk_util.c
src/refresh/vkpt/vk_util.h

Given it is mainly provided by debugging tools, always enabling it will conveniently provide object names when using such tools, without impacting the general case.
While we're at it, add debug labels to more objects.

Always use EXT_debug_marker extension, if available

---

CMakeLists.txt

CMake >= 3.15 provides a pretty convenient way, use that.

Simplify MSVC runtime selection

---

src/refresh/vkpt/main.c
src/refresh/vkpt/vkpt.h
src/unix/video/sdl.c

Came across some issues when trying to investigate #441.
Main things solved:
* VKPT renderer having incorrect belief of output resolution
* Use drawable size instead of window size (relevant in high DPI setups)
Also updated SDL2 for good measure.

Wayland-related fixes

---

src/refresh/vkpt/shader/vertex_buffer.h

That constant, introduced in #234, is a pretty conservative value, but unnecessarily large number.
The smallest number I found to work well is three - which makes sense, if you think about it: ASVGF only needs "history" from the previous frame, so we need: one for previous frame rendered, one for current frame rendering, and one more for upload.

Vastly reduce LIGHT_COUNT_HISTORY value

---

doc/server.md
inc/common/protocol.h
src/server/entities.c
src/server/main.c

...to be a bit closer to the upstream source again while dealing with #462.
My thinking behind keeping `MAX_PACKET_ENTITIES_OLD`:
Q2PRO introduced a larger `MAX_PACKET_ENTITIES` to accommodate remaster content, presumably because it was found it'll exceed the old limit.
In the same vein, should any further support for remastered content make it into Q2RTX, this may require an even larger `MAX_PACKET_ENTITIES` value due to use of PVS2. Keeping both constants may make adjustments easier.

Re-apply sv_max_packet_entities change, with fix

---

src/refresh/vkpt/draw.c

...since it's created together with pipelines.
Fixes a leak & validation error.

Destroy render_pass_stretch_pic when destroying pipelines

---

src/refresh/gl/gl.h
src/refresh/gl/mesh.c
src/refresh/gl/state.c

Our default `cl_gunscale` value of 0.25 results in the weapon clipping through the near plane. Adjust the near plane distance to work around this.

Fix view weapon clipping to near place in GL mode

---

src/refresh/vkpt/textures.c

They all showed up as `tex_image_views[i]` and `tex_image_views_mip0[i]` previously.

More useful tex_image_views debug labels

---

src/client/tent.c

Based on the cvar name, the additional condition was intended for RTX mode only, anyway.

Only evaluate cvar_pt_beam_lights when using the RTX renderer. For #487

---

src/client/client.h
src/client/effects.c

Commit 11bd9e53db08cb7921e36214940cdc0037ef5325 (picked from upstream) removed support for the 'decay' and 'velosity' (sic) dlight fields, but it turns out we still use them for the rail trail lights (oops).
Restore support for this fields, bringing back the pleasing fade-out of the rail trail lights.

Restore rail trail light effects
