NVIDIA/Q2RTX

src/client/main.c, src/refresh/vkpt/bsp_mesh.c, src/refresh/vkpt/main.c, src/refresh/vkpt/vk_util.c
These bugs were found using [PVS-Studio](https://www.viva64.com/en/pvs-studio/) (a static code analyzer).
=> Fix some bugs found by PVS-Studio

src/refresh/vkpt/main.c
A small convenience when switching around for testing.
=> Add autocompletion support for ray_tracing_api cvar

CMakeLists.txt, src/CMakeLists.txt
Comparing timedemos of an LTCG build vs the Steam release I get a few percent more FPS if I enable LTCG (and no other changes) - free performance! (A little.)
Still, be conservative and leave it default "off" for now.
=> Optionally build with IPO (LTCG)

CMakeLists.txt, cmake/compileShaders.cmake, src/CMakeLists.txt, src/refresh/vkpt/main.c, src/refresh/vkpt/shader/global_ubo.h, src/refresh/vkpt/shader/tone_mapping_apply.comp, src/refresh/vkpt/transparency.c
* I noticed some wrong buffer offset computations in update_transparency(), producing rendering errors
* Some miscellaneous fixes
* Merged in current "master"
PR to keep "your" copy of the branch updated.
=> Update "beam-int-shader" branch

src/client/effects.c
=> Fix typo in MZ_IONRIPPER sound (#141)

src/refresh/vkpt/main.c
I noticed that upon a map change the DRS scaling factor seems to "reset". Depending on how far away that is from playable frame rates this can take up to a few seconds to get there.
The changes here aim at preserving the DRS scaling factor, both between map changes and between game runs, leading to a shorter initial adjustment upon map changes.
=> Improve DRS behaviour

.github/workflows/build.yml
This fixes Linux build failures on recent GitHub action runs.
=> workflows: Run 'apt-get update' on Linux

doc/client.md, src/baseq2/g_phys.c, src/client/effects.c, src/client/entities.c, src/client/view.c, src/common/prompt.c, src/refresh/images.c, src/server/main.c
Pulls in a number of miscellaneous tweaks/fixes from Q2PRO.
=> Sync with Q2PRO

CMakeLists.txt
=> Update SDL2 to 2.26.1

src/refresh/vkpt/shader/light_lists.h
The motivation behind this change is a dark(er) seam I noticed next to certain sky polygons, their lighting computed through the "analytical" path. It can also be noticed on other light polygons, examples for both cases can be found below.
I determined that the lighting algorithm produced too many dark samples when lighting points close to the light polygon surface.
After researching a bit, it seemed to me as proper spherical triangle sampling might produce better results, and lo and behold, it does (after getting things to work right).
Before:
After:
(The third and sixth image is from a custom test map, I can provide it, if desired.)
Performance:
I compared "timedemo" runs with the old and new implementation.
On my 3080, at 4K resolution, the performance difference seems to appear almost …
=> Change sampling of polygonal light to use true spherical triangle sampling

.github/workflows/build.yml
SDL requires this to properly list displays & their modes. Should fix #254.
=> GH workflow: Install libxrandr-dev on Linux

baseq2/q2rtx.menu, src/client/ui/q2pro.menu
Some tweaks to `q2pro.menu` + matching updates to `q2rtx.menu`.
=> Sync with Q2PRO: Menu

doc/client.md, src/client/client.h, src/client/effects.c, src/client/entities.c, src/client/locs.c, src/client/main.c, src/client/newfx.c, src/client/tent.c, src/client/view.c, src/refresh/gl/mesh.c, src/refresh/gl/tess.c
Some changes that are (mostly) related to client-side effects.
=> Sync with Q2PRO: Effects

inc/shared/shared.h, src/baseq2/g_local.h, src/baseq2/g_utils.c, src/client/demo.c, src/client/gtv.c, src/client/main.c, src/client/view.c, src/common/common.c, src/server/mvd.c, src/server/mvd/client.c, src/server/save.c, src/server/user.c, src/server/world.c, src/shared/shared.c
Various changes involving `shared.{c,h}`.
=> Sync with Q2PRO: Misc 'shared' stuff

src/refresh/vkpt/shader/indirect_lighting.rgen, src/refresh/vkpt/shader/light_lists.h
Adjustments to avoid the noise reported in NVIDIA#287.
=> Improvements to spherical triangle sampling

inc/common/error.h, inc/shared/platform.h, src/common/bsp.c, src/common/error.c, src/refresh/gl/models.c, src/refresh/models.c, src/refresh/vkpt/models.c
Some additional data checking that was added to Q2PRO.
=> Check alignment of on-disk structures.

inc/common/error.h, src/common/error.c, src/common/files.c
Changes from Q2PRO related to archives:
Mostly improvements/enhancements related to  zip archives and some maintenance of pack file support.
=> Sync with Q2PRO: Filesystem archives

inc/format/md2.h, inc/format/pak.h, src/common/files.c
A minimal set of changes to start into the game and play the first level.
=> Basic Quake 2 Remastered support

inc/common/files.h, src/client/ascii.c, src/client/cin.c, src/client/console.c, src/client/demo.c, src/client/download.c, src/client/http.c, src/client/locs.c, src/client/main.c, src/client/sound/main.c, src/client/ui/demos.c, src/common/common.c, src/common/files.c, src/common/net/net.c, src/common/prompt.c, src/common/tests.c, src/refresh/gl/models.c, src/refresh/gl/sky.c, src/refresh/gl/surf.c, src/refresh/images.c, src/refresh/models.c, src/refresh/vkpt/bsp_mesh.c, src/refresh/vkpt/main.c, src/refresh/vkpt/material.c, src/refresh/vkpt/models.c, src/server/mvd.c, src/server/mvd/client.c, src/server/save.c, src/server/user.c
* A bit of new features, such as `FS_FLAG_LOADFILE` and .pkz seeking
* Some functions have been changed for simpler use, some renamed
* A couple of bugfixes as well
=> Sync with Q2PRO: Misc. filesystem changes

doc/client.md, inc/refresh/images.h, inc/refresh/refresh.h, src/client/console.c, src/client/refresh.c, src/client/screen.c, src/client/view.c, src/refresh/gl/gl.h, src/refresh/gl/texture.c, src/refresh/images.c, src/refresh/stb/stb.c, src/refresh/vkpt/main.c, src/refresh/vkpt/vkpt.h
Interesting changes:
* Texture override control
* Less annoying screenshot messages
* Error reporting improvements
=> Sync with Q2PRO: Image-related changes

src/refresh/vkpt/shader/path_tracer.h, src/refresh/vkpt/shader/vertex_buffer.h
There was feedback on #308 requesting documentation on one such (new) value. This also adds comments to the existing values.
=> Add comments to combined 'this_and_that' values in shaders

src/refresh/images.c
=> Fix use of _DEBUG

inc/common/msg.h, inc/common/sizebuf.h, src/client/input.c, src/common/msg.c, src/common/net/chan.c, src/common/sizebuf.c, src/server/user.c
A bunch of changes to sizebuf (and related message parsing changes) that will needed by subsequent changes from Q2PRO.
=> Sync with Q2PRO: sizebuf

inc/common/common.h, inc/common/zone.h, inc/refresh/models.h, inc/shared/list.h, inc/system/hunk.h, src/client/http.c, src/client/sound/ogg.c, src/client/ui/demos.c, src/client/ui/servers.c, src/common/common.c, src/common/cvar.c, src/common/net/chan.c, src/common/prompt.c, src/common/zone.c, src/refresh/vkpt/main.c, src/refresh/vkpt/transparency.c, src/refresh/vkpt/vertex_buffer.c, src/server/ac.c, src/server/game.c, src/server/main.c, src/server/mvd.c, src/server/mvd/client.c, src/server/mvd/game.c, src/server/send.c, src/server/user.c, src/unix/hunk.c, src/unix/sound/sdl.c, src/windows/hunk.c
A bunch of changes to the memory allocation functions.
=> Sync with Q2PRO: Memory allocation

inc/common/net/chan.h, src/client/client.h, src/client/entities.c, src/client/input.c, src/client/main.c, src/client/parse.c, src/client/predict.c, src/client/screen.c, src/client/view.c, src/common/net/chan.c, src/server/ac.c, src/server/commands.c, src/server/main.c, src/server/mvd.c, src/server/mvd/client.c, src/server/mvd/game.c, src/server/send.c, src/server/server.h, src/server/user.c
Upstream clean up, improvements to the "netchan" code.
=> Sync with Q2PRO: netchan

src/game/g_cmds.c
Small differences to upstream that are worth being ported over.
=> Some minor game changes

doc/server.md, inc/common/common.h, inc/common/utils.h, inc/system/system.h, src/common/common.c, src/common/utils.c, src/unix/system.c, src/unix/tty.c, src/unix/tty.h, src/windows/system.c
Changes to TTY/console output, including some more flexibility (custom console prefixes).
=> Sync with Q2PRO: TTY/console output

inc/refresh/models.h, src/refresh/gl/gl.h, src/refresh/gl/models.c, src/refresh/models.c, src/refresh/vkpt/models.c, src/refresh/vkpt/vkpt.h
Some changes from upstream, adjusting some model limits.
=> Sync with Q2PRO: Raise model limits

inc/system/system.h, src/client/client.h, src/client/console.c, src/client/download.c, src/client/http.c, src/client/ui/servers.c, src/common/utils.c, src/unix/system.c, src/windows/system.c
Upstream changes related to client downloads & use of curl.
=> Sync with Q2PRO: Client downloads/CURL

extern/CMakeLists.txt, src/client/download.c, src/client/http.c
More upstream changes related to CURL.
Required #356 to apply.
=> Sync with Q2PRO: Client downloads/CURL, pt. 2

src/client/main.c, src/server/commands.c, src/server/mvd/parse.c, src/unix/hunk.c, src/unix/system.c
Miscellaneous upstream changes that didn't quite fit anywhere yet.
=> Sync with Q2PRO: Misc

doc/client.md
Some small documentation changes from upstream.
=> Sync with Q2PRO: Docs

doc/server.md, src/server/commands.c, src/server/entities.c, src/server/world.c
Some upstream changes more or less related to dealing with entities.
=> Sync with Q2: map entities

doc/client.md, doc/server.md, inc/common/msg.h, src/client/client.h, src/client/demo.c, src/client/gtv.c, src/client/main.c, src/client/parse.c, src/common/msg.c, src/server/mvd.c, src/server/mvd/client.c, src/server/mvd/client.h, src/server/mvd/game.c, src/server/mvd/parse.c, src/server/save.c
Upstream improvements & fixes related to dealing with MVDs and demos.
=> Sync with Q2PRO: MVDs & demos

src/client/console.c, src/client/input.c, src/client/keys.c, src/client/main.c, src/common/prompt.c
Upstream changes that are related to input and console.
=> Sync with Q2PRO: Input things

src/client/tent.c
Upstream changes to client temp entity code.
=> Sync with Q2PRO: TENTs

src/client/main.c, src/client/precache.c, src/client/sound/dma.c, src/client/ui/menu.c, src/common/cmd.c, src/common/files.c, src/refresh/gl/models.c, src/refresh/models.c, src/refresh/vkpt/models.c, src/server/init.c, src/server/main.c, src/server/mvd/game.c, src/server/mvd/parse.c, src/server/send.c, src/server/user.c
Upstream changed some code to follow safer coding practices.
=> Sync with Q2PRO: Safer code

src/client/effects.c, src/client/entities.c, src/client/precache.c, src/client/sound/al.c, src/client/sound/main.c, src/client/view.c, src/common/cmodel.c, src/refresh/images.c, src/refresh/models.c
More replacements of statements patterned `if(!some_check) Com_Error(ERR_DROP, ...)` with `Q_assert(some_check)`.
=> Sync with Q2PRO: Assertive things

inc/common/net/net.h, src/client/gtv.c, src/common/net/net.c, src/common/net/unix.h, src/common/net/win.h, src/server/ac.c, src/server/mvd.c, src/server/mvd/client.c, src/unix/tty.c, src/windows/res/q2rtx.exe.manifest, src/windows/res/q2rtxded.exe.manifest
Upstream changed how it checks for new data on network connections.
=> Sync with Q2PRO: Network code

inc/refresh/models.h, src/refresh/gl/gl.h, src/refresh/models.c
Upstream changes to alias & sprite model structs.
=> Sync with Q2PRO: Model structs

src/unix/hunk.c, src/unix/system.c
Upstream changes in the Unix-specific functions.
=> Sync with Q2PRO: "unix"-specific updates

baseq2/q2rtx.menu, src/client/client.h, src/client/console.c, src/client/demo.c, src/client/entities.c, src/client/main.c, src/client/parse.c, src/client/precache.c, src/client/predict.c, src/client/ui/q2pro.menu
A variety of client-related changes from upstream.
=> Sync with Q2PRO: Client changes

src/CMakeLists.txt
=> Add CheckCCompilerFlag module

src/CMakeLists.txt
=> link libm for client target

src/refresh/vkpt/path_tracer.c, src/refresh/vkpt/uniform_buffer.c
=> Fix empty struct initializers

src/refresh/gl/models.c
Small fix that probably slipped through earlier.
=> Fix loading MD3 skins.

doc/client.md, src/client/client.h, src/client/download.c, src/client/main.c
"Enable filtering of commands server is allowed to stuff into client console."
=>  Sync with Q2PRO: stufftext whitelist

inc/common/mdfour.h, inc/common/utils.h, inc/shared/shared.h, license.txt, src/client/main.c, src/client/parse.c, src/common/common.c, src/common/mdfour.c, src/common/utils.c, src/server/main.c, src/server/mvd.c, src/server/user.c, src/shared/shared.c
Another bunch of upstream fixes that didn't quite fit anywhere else.
=> Sync with Q2PRO: Miscellaneous

inc/common/files.h, inc/server/server.h, inc/shared/files.h, inc/shared/game.h, src/client/ui/demos.c, src/common/files.c, src/server/game.c, src/server/main.c, src/server/server.h
Upstream a mechanism to provide an extended game API that's still compatible to the vanilla binary interface.
=> Sync with Q2PRO: Extended game API

inc/shared/game.h, src/server/game.c, src/server/server.h
Mostly related to game feature flags.
=> Sync with Q2PRO: Game fixes & improvements

src/client/keys.c, src/client/ui/playerconfig.c, src/client/ui/script.c, src/refresh/gl/surf.c, src/server/init.c, src/server/save.c, src/server/server.h
=> Sync with Q2PRO: More constifications

src/client/main.c, src/client/parse.c
A few client-change tweaks from upstream.
=> Sync with Q2PRO: Client tweaks

src/client/main.c, src/common/net/chan.c
Make use of the new `BIT` macro.
=> Sync with Q2PRO: Netchan code cleanup

inc/common/protocol.h, inc/shared/shared.h, src/client/client.h, src/server/main.c, src/server/mvd/client.h, src/server/mvd/game.c, src/server/server.h, src/server/user.c
There's always something that can be cleaned up!
=> Sync with Q2PRO: Some more cleanup

inc/shared/shared.h
Formatting change from upstream.
=> Sync with Q2PRO: Compress blank lines in shared.h.

src/server/entities.c, src/server/main.c, src/server/mvd/client.c, src/server/mvd/client.h, src/server/mvd/game.c, src/server/mvd/parse.c, src/server/server.h, src/server/user.c
Upstream changing some code to "more correct C".
=> Sync with Q2PRO: Remove a server-related hack

src/refresh/vkpt/shader/compositing.comp, src/refresh/vkpt/shader/light_lists.h
...which I happened to stumble across.
=> Remove some unused shader code

doc/client.md, inc/refresh/refresh.h, inc/shared/shared.h, src/client/client.h, src/client/entities.c, src/client/main.c, src/client/newfx.c, src/client/view.c, src/refresh/gl/mesh.c
Adds support for new effects from remaster.
Bonus: Enables client-side flashlight in GL mode as well.
=> Sync with Q2PRO: Extended effects

src/client/entities.c, src/refresh/gl/gl.h, src/refresh/gl/main.c
Support for entity scale & alpha.
Pretty straightforwards, seems to work fine in both GL and RTX.
=> Sync with Q2PRO: Implement entity alpha/scale

src/client/entities.c
Upstream changes specific to that effect.
=> Sync with Q2PRO: BFG lightramp

inc/refresh/refresh.h, src/client/client.h, src/client/download.c, src/client/effects.c, src/client/entities.c, src/client/newfx.c, src/client/precache.c, src/client/tent.c, src/refresh/images.c
Some upstream changes relating to (extended) client-side effects.
=> Sync with Q2PRO: Some more effects

inc/common/utils.h, src/client/http.c, src/common/utils.c
Upstream changes to make it more useful.
=> Sync with Q2PRO: Fixes & updates to Com_MakePrintable()
